# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.CharField(max_length=1000)),
                ('cena', models.PositiveIntegerField()),
                ('czas_przygotowania', models.PositiveIntegerField()),
                ('data_dodania', models.DateField()),
                ('data_aktualizacji', models.DateField()),
                ('danie_wegetarianskie', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
                ('opis', models.CharField(max_length=1000)),
                ('data_dodania', models.DateField()),
                ('data_aktualizacji', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='danie',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karta', to='menu.Menu'),
        ),
    ]
