# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_danie_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danie',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
