# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20170323_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danie',
            name='nazwa',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
