# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20170328_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.PositiveIntegerField()),
                ('preparation_time', models.PositiveIntegerField()),
                ('added_date', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('vegetarian', models.BooleanField()),
                ('foto', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='danie',
            name='menu',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='data_aktualizacji',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='nazwa',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='data_dodania',
        ),
        migrations.AddField(
            model_name='menu',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Danie',
        ),
        migrations.AddField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emenu', to='menu.Menu'),
        ),
    ]
